name: Ontime build

on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project packages
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: pnpm build

      - name: Electron - Build app
        run: pnpm dist-win

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: './apps/electron/dist/ontime-win64.exe'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
